# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactNativePlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

  # Pods for reactNativePlayground

  target 'reactNativePlayground-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNativePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativePlayground-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativePlayground-tvOS

  # target 'reactNativePlayground-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
